// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_essai.models;

#nullable disable

namespace project_essai.Migrations
{
    [DbContext(typeof(machineDbContext))]
    [Migration("20240912181453_last_version_application")]
    partial class last_version_application
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inspection", b =>
                {
                    b.Property<int>("IdInspection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInspection"));

                    b.Property<string>("CodeElementSection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeEquipement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeFamille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateElement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInspection")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdIntervenant")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdateUser")
                        .HasColumnType("int");

                    b.Property<string>("NumeroInter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeMaintenance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urgence")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInspection");

                    b.ToTable("Inspection", "dbo");
                });

            modelBuilder.Entity("project_essai.Models.Annuel", b =>
                {
                    b.Property<int>("IdAnnuel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnnuel"));

                    b.Property<bool>("ChaqueMens")
                        .HasColumnType("bit");

                    b.Property<string>("CodeFamille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeSection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("De")
                        .HasColumnType("datetime2");

                    b.Property<int>("JourWeekMens")
                        .HasColumnType("int");

                    b.Property<bool>("LeMens")
                        .HasColumnType("bit");

                    b.Property<int>("SecondeMens")
                        .HasColumnType("int");

                    b.Property<string>("element")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("joirMois")
                        .HasColumnType("int");

                    b.Property<int>("parMois")
                        .HasColumnType("int");

                    b.HasKey("IdAnnuel");

                    b.ToTable("Annuel", "dbo");
                });

            modelBuilder.Entity("project_essai.Models.Element", b =>
                {
                    b.Property<int>("IdElement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdElement"));

                    b.Property<int?>("AlerteAvant")
                        .HasColumnType("int");

                    b.Property<string>("CodeFamille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeSection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Debut")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("DureeIntervention")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Fin")
                        .HasColumnType("time");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdateUser")
                        .HasColumnType("int");

                    b.Property<int?>("NbOccurence")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOccurrence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePreventive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeElement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdElement");

                    b.ToTable("Elements", "dbo");
                });

            modelBuilder.Entity("project_essai.Models.Hebdomadaire", b =>
                {
                    b.Property<int>("IdHebdomadaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHebdomadaire"));

                    b.Property<string>("CodeFamille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeSection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<int>("RepeterSemaine")
                        .HasColumnType("int");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.Property<string>("element")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHebdomadaire");

                    b.ToTable("Hebdomadaire", "dbo");
                });

            modelBuilder.Entity("project_essai.Models.Intervenant", b =>
                {
                    b.Property<int?>("IdIntervenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdIntervenant"));

                    b.Property<bool?>("AideIntervenant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fonction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEquipe")
                        .HasColumnType("int");

                    b.Property<int?>("IdSite")
                        .HasColumnType("int");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdateUser")
                        .HasColumnType("int");

                    b.HasKey("IdIntervenant");

                    b.ToTable("Intervenants", "dbo");
                });

            modelBuilder.Entity("project_essai.Models.Intervention", b =>
                {
                    b.Property<string>("CodeIntervention")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("AideIntervenant")
                        .HasColumnType("bit");

                    b.Property<string>("CausePanne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ChangementPiece")
                        .HasColumnType("bit");

                    b.Property<bool?>("Cloture")
                        .HasColumnType("bit");

                    b.Property<string>("CodeDemande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreateReel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateHeureCloture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateHeureIntervention")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdIntervention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdIntervention"));

                    b.Property<int?>("IdPrestataire")
                        .HasColumnType("int");

                    b.Property<int?>("IdTypeIntervention")
                        .HasColumnType("int");

                    b.Property<int?>("Intervenant")
                        .HasColumnType("int");

                    b.Property<bool?>("InterventionExterne")
                        .HasColumnType("bit");

                    b.Property<bool?>("InterventionPause")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdateUser")
                        .HasColumnType("int");

                    b.Property<string>("OriginePanne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Terminer")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeIntervention");

                    b.ToTable("Interventions", "dbo");
                });

            modelBuilder.Entity("project_essai.Models.Mensuel", b =>
                {
                    b.Property<int>("IdMensuel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMensuel"));

                    b.Property<string>("CodeFamille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeSection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Jour")
                        .HasColumnType("bit");

                    b.Property<int>("JourweekMens")
                        .HasColumnType("int");

                    b.Property<bool>("LeMens")
                        .HasColumnType("bit");

                    b.Property<int>("LeNbMois")
                        .HasColumnType("int");

                    b.Property<int>("NbMois")
                        .HasColumnType("int");

                    b.Property<int>("SecondMens")
                        .HasColumnType("int");

                    b.Property<string>("element")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("jourMois")
                        .HasColumnType("int");

                    b.HasKey("IdMensuel");

                    b.ToTable("Mensuel", "dbo");
                });

            modelBuilder.Entity("project_essai.models.DemandeInterventions", b =>
                {
                    b.Property<string>("CodeDemande")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Chaine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeEquipement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeOrdre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodeUrgence")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreateReel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateHeureDemande")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EtatDemande")
                        .HasColumnType("int");

                    b.Property<string>("EtatMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdDemande"));

                    b.Property<int?>("IdPanne")
                        .HasColumnType("int");

                    b.Property<int?>("IdTypeDemande")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdateUser")
                        .HasColumnType("int");

                    b.Property<bool?>("MaintenanceTSV")
                        .HasColumnType("bit");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Priorite")
                        .HasColumnType("int");

                    b.Property<string>("ResumePanne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Terminer")
                        .HasColumnType("int");

                    b.Property<string>("TypeMaintenance")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeDemande");

                    b.ToTable("DemandeInterventions", "dbo");
                });

            modelBuilder.Entity("project_essai.models.Utilisateur", b =>
                {
                    b.Property<int>("Matricule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matricule"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdAtelier")
                        .HasColumnType("int");

                    b.Property<int>("IdGrade")
                        .HasColumnType("int");

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.HasKey("Matricule");

                    b.ToTable("Utilisateurs", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
