name: project_essai_flutter
description: A new Flutter project.
publish_to: 'none' # Remplacer par une URL si vous souhaitez publier ce package

version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  fl_chart: 0.40.6
  provider: ^6.0.3
  intl: ^0.18.0
  flutter_datetime_picker: ^1.4.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2


flutter:
  uses-material-design: true
  assets:
    - assets/logo.jfif
 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jfif" 
