name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: |
         flutter pub get
        
        

    - name: Exécuter les tests
      run: |
         flutter test
        
       

    - name: Déboguer les tests échoués
      if: failure()  
      run: |
        # Afficher les logs
        echo "Les tests ont échoué. Voici les logs :"
        # Ici, vous pouvez ajouter d'autres commandes pour afficher des logs ou des résultats de tests
