name: CI/CD Pipeline for .NET and Flutter

# Déclenchement du workflow sur push ou pull request sur la branche principale
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job pour tester et construire le backend .NET
  backend:
    runs-on: windows-latest   

    steps:
      # Étape 1: Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Installer .NET Core (vérifiez la version de .NET)
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'   

      # Étape 3: Restaurer les dépendances backend
      - name: Restore dependencies
        run: dotnet restore ./project_essai/project_essai

      # Étape 4: Construire le projet backend
      - name: Build backend
        run: dotnet build --configuration Release ./project_essai/project_essai

      # Étape 5: Exécuter les tests backend
      - name: Run tests
        run: dotnet test ./project_essai/project_essai

  # Job pour tester et construire le frontend Flutter
  frontend:
    runs-on: windows-latest  

    steps:
      # Étape 1: Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Installer Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'   

      # Étape 3: Créer le dossier 'test' s'il n'existe pas
      - name: Create test folder if not exists
        run: |
          if [ ! -d "project_essai_flutter/test" ]; then
            mkdir project_essai_flutter/test
          fi

      - name: Navigate to project directory
        run: cd project_essai_flutter

      - name: Install dependencies
        run: |
          cd project_essai_flutter  
          flutter pub get

      - name: Run tests
        run: |
          cd project_essai_flutter  
          flutter test

      - name: Build apk
        run: |
          cd project_essai_flutter  
          flutter build apk --release
